# Generated by Django 5.1.4 on 2025-09-26 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='image',
            field=models.ImageField(blank=True, default='images/no_image_available.png', null=True, upload_to='blog_images/'),
        ),
    ]
