# Generated by Django 5.1.4 on 2025-01-21 09:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_tag_orders_tag'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders',
            name='tag',
        ),
        migrations.AddField(
            model_name='products',
            name='tag',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='products.tag'),
        ),
    ]
