# Generated by Django 5.1.4 on 2025-01-21 09:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_remove_orders_tag_products_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='tag',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='products.tag'),
        ),
    ]
